version: "3.9"

services:
  licitanet:
    container_name: licitanet_valida
    image: ghcr.io/walterrosa2/licitanet_valida:1.0.4
    restart: unless-stopped

    # Monta TODA a pasta do projeto dentro do container
    volumes:
      - .:/app


    environment:
      # Diret√≥rio base de dados (estado do pipeline)
      BASE_DIR: /app/data

      PATH_INBOX: /app/data/inbox
      PATH_PROCESSING: /app/data/processing
      PATH_OUTBOX: /app/data/outbox
      PATH_DONE: /app/data/done
      PATH_ERROR: /app/data/error
      PATH_LOGS: /app/data/logs
      PATH_EVIDENCIAS: /app/data/evidencias

    ports:
      - "8599:8599"
